var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                oo              ",
   "                                                            xxx    xxx          ",
   "                                                           x!!!x  x!!!x         ",
   "                           b                      b       x!!!!!xx!!!!!x        ",
   "                         xxxxx                            x!!!!!!!!!!!!x        ",
   "                         x!!vx      o                     x!!!!!!!!!!!!x        ",
   "                      xxxxxx                               x!!!!!!!!!!x         ",
   "                      x            xxxx                     x!!!!!!!!x          ",
   "                   xxxx               x                      x!!!!!!x       xx  ",
   "  xx               x                  xxxx  o                 x!!!!x         x  ",
   "  x             xxxx                     x                     x!!x          x  ",
   "  x             x                        xxxxx                               x  ",
   "  x          xxxx      o                                                     x  ",
   "  x  @       x      s                o           o                           x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxx  ",
   "                          x       x                x   x   x                    ",
   "                          x!!!!!!!x                x!!!!!!!x                    ",
   "                          x!!!!!!!x                x!!!!!!!x                    ",
   "                          xxxxxxxxx                xxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             xxx  ",
   "                                                                                                     o       x!x  ",
   "                                  xxxxxxxxxxxxxxxxxx                                                xxx      x!x  ",
   "                                  xx!!!!!!!!!!!!!!xx                                               x!!!x     x!x  ",
   "                                  x!!!xxxxxxxxxx!!!x                                              x!!!!!x    x!x  ",
   "                                  x!!xx        xx!!x                                             x!!!!!!!x   x!x  ",
   "                                  x!!x  x    x  x!!x                                          xxxx!!!!!!!xxxxx!x  ",
   "                                  xxvx  x    x  xvxx                                          x!!!!!!!!!!!!!!!!x  ",
   "                                        x    x                                            xxxxxxxxvxxxxxxxvxxxxx  ",
   "                                                                  xxxxxxx                                         ",
   "                                      x        x                  x!!!!!x                                         ",
   "                                       x      x                   xxxxxxx        xxx                              ",
   "                                        xxxxxx                                   x x                              ",
   "                                                o    s                             x     s                        ",
   "                                               x     x                             xx    s                        ",
   "                                               x     x                             x                           xx ",
   "                                               xx    x                   x         x                           xx ",
   "                                               x     x                   x    ooo  x                  b         x ",
   "                                               x     x   xxxxx           x   xxxxxxxxx                          x ",
   "                                  o            x     x                   x   x              xxxxx   xxxxx   xxxxx ",
   "     @        o        o                       x    xx                   x!!!x               x  x   x   x   x     ",
   "    xxx                         x   x          x     x   =  =  =  =  x   xxxxx   xxxxxx      x  x!!!x   x!!!x     ",
   "    x x      xx       xx       xx   xx         x     xxxxxxxxxxxxsxxxx     o     x x         x  x!!!x   x!!!x     ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x           x x         x  x!!!x   x!!!x     ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!xx       xx!!!!!!xx     x!!!!!!!!!!!!!!!xxxxxxxxxxxxx x    o    x  x!!!x   x!!!x     ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!x    o           o     xx!!!!!!!!!!!!!!!              xxxxxxxxxxx  x!!!x   x!!!x     ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!x          o          xx!!!!!!!!!!!!!!!!                           xxxxx   xxxxx     ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!                                             ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                             ",
   "!!!!x x!!!!!!xx!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                             "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         o                   x                                                ",
   "                                                                                                              ",
   "                                                             |                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                       xxxxx                                                                  ",
   "                                       x!!!x                              xxx                                 ",
   "                                      oxxvxx                 x           x                                    ",
   "                                      xx   x                 x    oo    x                                     ",
   "                                       x   x                 x   oooo   x       xxx                           ",
   "                                       x   x                 x       =  x      x!!!x                          ",
   "                               x      ox   x       x   x     xxxxxxxxxxxx       xxx                           ",
   "     x                x       x       xx   x       x o x      x                                               ",
   "     x!!!!!!!!!!!!!!!!x      x         x   xxxxxxxxx   xxxxxxxx              x x                              ",
   "     xxxxxxxxxxxvxxxvxx      x         x   x           x    x!!!x                                             ",
   "                              x       ox   x     =     x                     xxx                              ",
   "                               s      xx!!!xx          x                                                      ",
   "                                x      x!!!x           x                                                      ",
   "                                 x     x!!!x          xx            x   x                     b               ",
   "                                 x    ox!!!x      =    x      o                                               ",
   "                                x     xx!!!xx          x                                                      ",
   "                               x       x!!!x           x      x                  s                            ",
   "                              x        x!!!x           x              x        x   x                          ",
   "                             xxxxx    xxxxxx    o o    x!!!!!!!!!!!!!!x                                       ",
   "                            xxxxxxx o xxxxxxxx         x!!!!!!!!!!!!!!x                                       ",
   "                            x                x   xxxxxxxxxxxxxxxxxxxxxxx                                      ",
   "                           x                  x                                                               ",
   "  xxx                     x       xxxxx        x                                 x                       xxx  ",
   "  x x                     x      xxxxxxx       x                                xxx                      x x  ",
   "  x                       xx      xxvxx       xxxxxxxxx                        xxxxx                       x  ",
   "  x                        x                  x                               x!!!!!x                      x  ",
   "  x                         x                x                                 x!!!x                       x  ",
   "  x                                         x       |xxxx     |xxxx   o       xxxvxxx                      x  ",
   "  x |                               o      x                                                               x  ",
   "  x                           xx         xx                                                         ooo    x  ",
   "  x                           x    xxx    x   o            o                                        o o    x  ",
   "  x                           xxxxxxxxxxxxx        x     x    x         x                  xx       ooo    x  ",
   "  x      @               =   xx!!!!!!!!!!!x        x!!!!!x    x!!!!!!!!!x                  xx              x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxx  ",
   "                                                         x    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x            ",
   "                                                         x                                       x            ",
   "                                                         x                                       x            ",
   "                                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            "],
   ["                                                                     ",
   "                                                                x     ",
   "                        @                                       x     ",
   "      x              x  x  xxxxxxx  xxxxxxx  xxxxxxx  xxxxxx    x     ",
   "       x            x   x  x     x  x     x  x     x  x    x          ",
   "        x    xx    x    x  x     x  x     x  xxxxxxx  x         x     ",
   "         x  x  x  x     x  x     x  x     x  x        x        xxx    ",
   "          x      x      x  x     x  x     x  xxxxxxx  x         x     ",
   "                                                                      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
